/** Korean UI copy for 파도파도. Language buttons only store selection for now. */
export const UI_TEXT = {
  serviceName: "파도파도",
  serviceTagline: "바다와 사람을 잇는 착한 발걸음",
  searchPlaceholder: "지역, 장소, 키워드로 검색해보세요",
  searchButton: "검색",
  searchHintPrefix: "검색어",
  searchHintSuffix: "검색 기능은 다음 단계에서 연결됩니다.",
  searchNoResults: "검색 결과가 없습니다.",
  searchResultsLabel: "검색 결과",
  weather: "날씨",
  notifications: "알림",
  favorites: "즐겨찾기",
  login: "로그인",
  language: "언어",
  openMenu: "메뉴 열기",
  closeMenu: "메뉴 닫기",
  mapComingSoon: "지도 API 연결 예정",
  fitAllMarkers: "전체 마커 보기",
  zoomIn: "확대",
  zoomOut: "축소",
  currentLocation: "현재 위치",
  scaleLabel: "지도",
  selectPlace: "지도에서 장소를 선택해주세요.",
  noPlaces: "현재 카테고리에 표시할 장소가 없습니다.",
  addFavorite: "즐겨찾기 추가",
  removeFavorite: "즐겨찾기 해제",
  directions: "길찾기",
  directionsNotice: "길찾기 기능은 다음 단계에서 제공됩니다.",
  targetFish: "주요 대상 어종",
  nearbyMarket: "주변 수산시장",
  distance: "이동 거리",
  beginnerFriendly: "초보자 추천",
  parkingAvailable: "주차 가능",
  toiletAvailable: "화장실 있음",
  safetyFacilities: "안전시설",
  verified: "검증됨",
  ploggingPromoTitle: "깨끗한 바다를 위해",
  ploggingPromoBody: "함께 플로깅해요!",
  ploggingPromoCta: "코스 보러가기",
  locationPermissionNeeded: "현재 위치 권한이 필요합니다.",
  locationUnavailable: "현재 위치를 확인할 수 없습니다.",
  locationUnsupported: "이 브라우저에서는 위치 정보를 지원하지 않습니다.",
  locationTimeout: "위치 확인 시간이 초과되었습니다.",
  noticeDismiss: "닫기",
  kakaoKeyMissingTitle: "카카오맵 API 키가 설정되지 않았습니다.",
  kakaoKeyMissingBody:
    ".env.local에 NEXT_PUBLIC_KAKAO_MAP_APP_KEY를 등록해주세요.",
  kakaoLoadFailedTitle: "지도를 불러오지 못했습니다.",
  kakaoLoadFailedBody:
    "카카오 개발자 콘솔에서 [제품 설정] → [카카오맵] → [활성화 설정]을 ON으로 바꾼 뒤 다시 시도해주세요. 도메인(http://localhost:3000)도 JavaScript SDK 도메인에 등록되어 있어야 합니다.",
  kakaoRetry: "다시 시도",
  mapLoading: "지도를 불러오는 중…",
} as const;

export type UiTextKey = keyof typeof UI_TEXT;
