/** Korean UI copy for 파도파도. Language buttons only store selection in phase 2. */
export const UI_TEXT = {
  serviceName: "파도파도",
  serviceTagline: "바다와 사람을 잇는 착한 발걸음",
  searchPlaceholder: "지역, 장소, 키워드로 검색해보세요",
  searchButton: "검색",
  searchHintPrefix: "검색어",
  searchHintSuffix: "검색 기능은 다음 단계에서 연결됩니다.",
  weather: "날씨",
  tide: "물때",
  notifications: "알림",
  favorites: "즐겨찾기",
  login: "로그인",
  language: "언어",
  openMenu: "메뉴 열기",
  closeMenu: "메뉴 닫기",
  mapComingSoon: "지도 API 연결 예정",
  listView: "목록 보기",
  zoomIn: "확대",
  zoomOut: "축소",
  currentLocation: "현재 위치",
  scaleLabel: "500m",
  selectPlace: "지도에서 장소를 선택해주세요.",
  noPlaces: "현재 표시할 장소가 없습니다.",
  addFavorite: "즐겨찾기 추가",
  removeFavorite: "즐겨찾기 해제",
  directions: "길찾기",
  directionsNotice: "길찾기 기능은 지도 API 연결 단계에서 제공됩니다.",
  targetFish: "주요 대상 어종",
  nearbyMarket: "주변 수산시장",
  distance: "이동 거리",
  beginnerFriendly: "초보자 추천",
  parkingAvailable: "주차 가능",
  toiletAvailable: "화장실 있음",
  safetyFacilities: "안전시설",
  todayTide: "오늘의 물때",
  highTide: "만조",
  lowTide: "간조",
  tideStatus: "상태",
  ploggingPromoTitle: "깨끗한 바다를 위해",
  ploggingPromoBody: "함께 플로깅해요!",
  ploggingPromoCta: "코스 보러가기",
  locationComingSoon: "현재 위치 기능은 지도 API 연결 단계에서 제공됩니다.",
  listComingSoon: "목록 보기 기능은 다음 단계에서 제공됩니다.",
  noticeDismiss: "닫기",
} as const;

export type UiTextKey = keyof typeof UI_TEXT;
